name: Java CI with Maven

on:
  push:
    branches: ["main"] # Si attiva ogni volta che fai push su main
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Scarica il tuo codice sulla macchina virtuale

      - name: Set up JDK 17 # Assicurati che la versione coincida con il tuo progetto
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml # Compila e crea il file .jar

      - name: Run Tests
        run: mvn test # Esegue i test unitari
