# ===============================
# CONFIGURAZIONE DATABASE
# ===============================

# URL di connessione:
# jdbc:mysql://HOST:PORT/DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/hr

# Username del database
spring.datasource.username=root

# Password del database (metti la tua)
spring.datasource.password=PASSWORD

# Driver JDBC per MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# CONFIGURAZIONE JPA / HIBERNATE
# ===============================

# Non modifica il database automaticamente
spring.jpa.hibernate.ddl-auto=none

# Mostra le query SQL in console (utile per capire cosa succede)
spring.jpa.show-sql=true

# Dialect per MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Porta del server
server.port=8080
