name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Questo abilita il tasto Play

jobs:
  build:
    runs-on: ubuntu-latest

    # Impostiamo la cartella di lavoro per tutto il Job
    defaults:
      run:
        working-directory: ./programma_20_2_26

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      # Ora Maven troverà il pom.xml perché "si trova" già dentro la cartella giusta
      run: mvn -B package

    - name: Run Tests
      run: mvn test
